---
- hosts: all
  roles:
    - role: "{{ playbook_dir }}"
- hosts: all
  roles:
    - role: "{{ playbook_dir }}"
      influxdb_config:
        reporting_disabled: false
        bind_address: 127.0.0.1:8088
        meta:
          dir: /var/lib/influxdb/meta
          retention_autocreate: true
          logging_enabled: true
        data:
          dir: /var/lib/influxdb/data
          wal_dir: /var/lib/influxdb/wal
          wal_fsync_delay: "0s"
          index_version: inmem
          trace_logging_enabled: false
          query_log_enabled: false
          validate_keys: false
          cache_max_memory_size: 1g
          cache_snapshot_memory_size: 25m
          cache_snapshot_write_cold_duration: 10m
          compact_full_write_cold_duration: 4h
          max_concurrent_compactions: 0
          compact_throughput: 48m
          compact_throughput_burst: 48m
          tsm_use_madv_willneed: false
          max_series_per_database: 1000000
          max_values_per_tag: 100000
          max_index_log_file_size: 1m
          series_id_set_cache_size: 100
        coordinator:
          write_timeout: 10s
          max_concurrent_queries: 0
          query_timeout: "0s"
          log_queries_after: "0s"
          max_select_point: 0
          max_select_series: 0
        retention:
          enabled: true
          check_interval: 30m
        shard_precreation:
          enabled: true
          check_interval: 10m
          advance_period: 30m
        monitor:
          store_enabled: true
          store_database: _internal
          store_interval: 10s
        http:
          enabled: true
          flux_enabled: false
          flux_log_enabled: false
          bind_address: :8086
          auth_enabled: false
          realm: InfluxDB
          log_enabled: true
          suppress_write_log: false
          access_log_path: ""
          access_log_status_filters: []
          write_tracing: false
          pprof_enabled: true
          pprof_auth_enabled: false
          debug_pprof_enabled: false
          ping_auth_enabled: false
          https_enabled: false
          https_certificate: /etc/ssl/influxdb.pem
          https_private_key: ""
          shared_secret: ""
          max_row_limit: 0
          max_connection_limit: 0
          unix_socket_enabled: false
          bind_socket: /var/run/influxdb.sock
          max_body_size: 25000000
          max_concurrent_write_limit: 0
          max_enqueued_write_limit: 0
          enqueued_write_timeout: 0
        logging:
          format: auto
          level: info
          suppress_logo: false
        subscriber:
          enabled: true
          http_timeout: 30s
          insecure_skip_verify: false
          ca_certs: ""
          write_concurrency: 40
          write_buffer_size: 1000
        graphite:
          enabled: false
          database: fraphite
          retention_policy: ""
          bind_address: :2003
          protocol: tcp
          consistency_level: one
          batch_size: 5000
          batch_pending: 10
          batch_timeout: 1s
          udp_read_buffer: 0
          separator: .
          tags:
            - region=us-east
            - zone=1c
          templates:
            - "*.app env.service.resource.measurement"
        collectd:
          enabled: false
          bind_address: :25826
          database: collectd
          retention_policy: ""
          typesdb: /usr/local/share/collectd
          security_level: none
          auth_file: /etc/collectd/auth_file
          batch_size: 5000
          batch_pending: 10
          batch_timeout: 10s
          read_buffer: 0
          parse_multivalue_plugin: split
        opentsdb:
          enabled: false
          bind_address: :4242
          database: opentsdb
          retention_policy: ""
          consistency_level: one
          tls_enabled: false
          certificate: /etc/ssl/influxdb.pem
          log_point_errors: true
          batch_size: 1000
          batch_pending: 5
          batch_timeout: 1s
        udp:
          enabled: false
          bind_address: :8089
          database: udp
          retention_policy: ""
          precision: ""
          batch_size: 5000
          batch_pending: 10
          batch_timeout: 1s
          read_buffer: 0
        continuous_queries:
          enabled: true
          log_enabled: true
          query_stats_enabled: false
          run_interval: 1s
        tls:
          ciphers:
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          min_version: tls1.2
          max_version: tls1.2
